name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CLEANUP_DELAY: ["1500"]
        DEPLOY_STORAGE_DELAY: ["1500"]
        DEPLOY_FUNCTIONS_DELAY: ["10000"]
        DEPLOY_DB_DELAY: ["1500"]
        TIMEOUT_DELAY: ["120000"]
        ITERATION: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Get Firebase CLI version
        id: firebase-cli-version
        shell: bash
        run: >-
          echo "FIREBASE_CLI_VERSION=$(pnpm list firebase-tools --parseable | tail -n 1 | cut -d '@'
          -f2)" >> $GITHUB_OUTPUT
      - name: Setup Firebase Emulators cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/firebase/emulators
          key: >-
            ${}-firebase-emulators-${{
            steps.firebase-cli-version.outputs.FIREBASE_CLI_VERSION }}
      - name: Build es6
        run: pnpm build:es6
      - name: Build cjs
        run: pnpm build:cjs
      - name: Build types
        run: pnpm build:types
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
        env:
          CLEANUP_DELAY: ${{ matrix.CLEANUP_DELAY }}
          DEPLOY_STORAGE_DELAY: ${{ matrix.DEPLOY_STORAGE_DELAY }}
          DEPLOY_FUNCTIONS_DELAY: ${{ matrix.DEPLOY_FUNCTIONS_DELAY }}
          DEPLOY_DB_DELAY: ${{ matrix.DEPLOY_DB_DELAY }}
          TIMEOUT_DELAY: ${{ matrix.TIMEOUT_DELAY }}
          ITERATION: ${{ matrix.ITERATION }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
