name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:types

  test-independence:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ITERATION: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install
      - id: firebase-cli-version
        shell: bash
        run: >-
          echo "FIREBASE_CLI_VERSION=$(pnpm list firebase-tools --parseable | tail -n 1 | cut -d '@'
          -f2)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ~/.cache/firebase/emulators
          key: >-
            ${}-firebase-emulators-${{
            steps.firebase-cli-version.outputs.FIREBASE_CLI_VERSION }}
      - run: pnpm build:es6
      - run: pnpm build:cjs
      - run: pnpm build:types
      - run: pnpm install:functions
      - run: pnpm test:independence
        env:
          ITERATION: ${{ matrix.ITERATION }}

  release:
    needs: [lint-and-typecheck, test-independence]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install
      - run: pnpm build:es6
      - run: pnpm build:cjs
      - run: pnpm build:types
      - run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
