name: Release
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SHARD: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Get Firebase CLI version
        id: firebase-cli-version
        shell: bash
        run: >-
          echo "FIREBASE_CLI_VERSION=$(pnpm list firebase-tools --parseable | tail -n 1 | cut -d '@'
          -f2)" >> $GITHUB_OUTPUT
      - name: Setup Firebase Emulators cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/firebase/emulators
          key: >-
            ${}-firebase-emulators-${{
            steps.firebase-cli-version.outputs.FIREBASE_CLI_VERSION }}
      - name: Build es6
        run: pnpm build:es6
      - name: Build cjs
        run: pnpm build:cjs
      - name: Build types
        run: pnpm build:types
      - name: Lint
        run: pnpm lint
      - run: pnpm test:types
      - run: pnpm install:functions
      - run: pnpm firebase --project demo emulators:exec "vitest --run --outputDiffLines 1000 --shard=${{ matrix.SHARD }}/10"
        env:
          CLEANUP_DELAY: "3000"
          DEPLOY_STORAGE_DELAY: "3000"
          DEPLOY_FUNCTIONS_DELAY: "15000"
          DEPLOY_DB_DELAY: "3000"
          TIMEOUT_DELAY: "90000"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm semantic-release
